import "./globals.css";
import Link from "next/link";
import LoginBtn from "@/app/LoginBtn";
import {getServerSession} from "next-auth";
import {authOptions} from "@/pages/api/auth/[...nextauth]";
import LogOutBtn from "@/app/LogOutBtn";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children}) {
    let session = await getServerSession(authOptions)
    return (
        <html lang="en">
        <body>
        <div className="navbar">
            <Link href="/" className="logo">Appleforum</Link>
            <Link href="/list">List</Link>
            <Link href="/write">Write</Link>
            <Link href="/register">Register</Link>
            {
                session == null ? <LoginBtn/> : <span>{session.user.name} <LogOutBtn/></span>
            }

        </div>
        {children}
        </body>
        </html>
    );
}
